version: "3.3"
services:
  mysqldb:
    container_name: aymen
    image: "mysql:latest"
    # restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: spring
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
  app:
    depends_on:
      - mysqldb
    image: aymenarfaoui/devops_achat:latest
    restart: on-failure
    ports:
      - 8089:8089
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true